### ISSUE TITLE
Add your local tech community slack! :) #Hacktoberfest

### ISSUE THREAD

**Issue by ladyleet** [ladyleet/tech-community-slacks#38]
Hey #hacktoberfest folk! Submit a PR for your local tech community slack! Add the actual signup link though please! :) Thanks!

**Comment by jimthedev** [comment]
Hey! Great idea.  I have [a site](https://o.hai.mn) that is a list of many of the various tech slacks in Minnesota. People put in PRs, etc. Can I list that site (which links to all) or would I need to manually put each slack?

**Comment by ladyleet** [comment]
@jimthedev it would be great to have both! :)
