### ISSUE TITLE
Can't access communities that have URLs ending with *.slack.com/messages/*

### ISSUE THREAD

**Issue by 1andee** [ladyleet/tech-community-slacks#59]
URLs should point somewhere an invite can be obtained.

**Comment by ladyleet** [comment]
@1andee yes i know - i still add them and ask folks to update when they find the link. feel free to update the ones you see! :) 💯

**Comment by 1andee** [comment]
Mostly fixed in PR #60

**Comment by 1andee** [comment]
There's a bunch more ending with *.slack.com that I didn't notice at first. I'll work away at them incrementally.

**Comment by ladyleet** [comment]
@1andee def request invite page where possible :)

**Comment by ladyleet** [comment]
Thx for the great Pr with fixes! :) closing this issue.
