### ISSUE TITLE
Link of Technologies/PWA Slack is broken

### ISSUE THREAD

**Issue by Aarbel** [ladyleet/tech-community-slacks#94]
hi @EdenSG !

the link of PWA's Slack link is broken, could you update it ? (we work on a PWA right now ^^)
=> cf https://github.com/ladyleet/tech-community-slacks/blob/master/README.md#technologies

Thanks a lot ! :open_hands:

**Comment by EdenSG** [comment]
Hi @Aarbel, I'm not sure why you've mentioned me for this, but I've gone and made a PR because why not 😁

**Comment by ladyleet** [comment]
closed and fixed!

**Comment by Aarbel** [comment]
Thanks a lot @EdenSG, i just saw you wrote it ;) perfect !
